# This workflow will upload a Python Package using setup.py/twine when a release is created
# For more information see:
# https://help.github.com/en/actions/language-and-framework-guides/using-python-with-github-actions#publishing-to-package-registries

name: Create Release

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    - name: Install dependencies
      run: |
        python -m pip install build
        pip install build twine setuptools
    - name: Build and publish
      env:
        TWINE_USERNAME: __token__
        # The PYPI_PASSWORD must be a pypi token with the "pypi-" prefix with sufficient permissions to upload this package
        # https://pypi.org/help/#apitoken
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      run: |
        python3 -m build
        twine upload dist/*
  make_cli_executable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Make Executable
        shell: bash
        run: |
          python -m pip install pyinstaller .
          pyinstaller cli.spec
      - name: Zip Output
        run: |
          &"C:/Program Files/7-Zip/7z.exe" a ./dist/doppkit-cli.zip ./dist/doppkit-cli.exe
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/doppkit-cli.zip
            dist/doppkit-cli.exe
  make_gui_executable:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Make Executable
        shell: bash
        run: |
          python -m pip install pyinstaller .[GUI]
          pyinstaller gui.spec
      - name: Zip Output
        run: |
          &"C:/Program Files/7-Zip/7z.exe" a ./dist/doppkit-gui.zip ./dist/doppkit-gui.exe
      - name: Upload Release Asset
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/doppkit-gui.zip
            dist/doppkit-gui.exe
